import type { AgentPermission } from "./reader";

export const LEGACY_AGENT_PERMISSIONS: Record<string, AgentPermission> = {
  "Meta-Planner": {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    edit: "deny",
    bash: "deny",
    webfetch: "deny",
    websearch: "deny",
    resolve_domain_id: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    dispatch_subagent: "allow",
    todowrite: "allow",
    safe_shell: {
      "*": "allow",
      "sha256sum *": "allow",
    },
    context7: "deny",
    skill: "allow",
    pandoc: "allow",
    safe_diff: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    safe_edit: {
      ".task_temp/**": "allow",
      "Task.DAG.json": "allow",
      "Project.graph": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/state/**": "deny",
      "contract.yaml": "deny",
    },
    safe_delete: {
      ".task_temp/**": "allow",
      "Task.DAG.json": "allow",
      "Project.graph": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/state/**": "deny",
      "contract.yaml": "deny",
    },
    safe_mkdir: {
      ".task_temp/**": "allow",
      "Task.DAG.json": "allow",
      "Project.graph": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/state/**": "deny",
      "contract.yaml": "deny",
    },
    safe_test: "deny",
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      ".task_temp/**": "allow",
      "Task.DAG.json": "allow",
      "Project.graph": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/state/**": "deny",
      "contract.yaml": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  Architect: {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    bash: "deny",
    edit: "deny",
    webfetch: "deny",
    websearch: "deny",
    safe_test: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    pandoc: "allow",
    resolve_domain_id: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    code_quality_check: "allow",
    safe_diff: "allow",
    safe_edit: {
      "contract.yaml": "allow",
      ".opencode/state/machine.json": "allow",
      ".opencode/context/**": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      "opencode.json": "deny",
      ".opencode/state/**": "deny",
      ".opencode/project.config.json": "deny",
      "PROJECT_REFERENCE.md": "deny",
      ".opencode/rules/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/legacy/subagent-preamble.md": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/plugins/**": "deny",
      ".opencode/**": "deny",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "booking_system_refactor/booking-backend/test/**": "deny",
    },
    safe_shell: {
      "node .opencode/scripts/mcp-tools/keystone-validate.js --hash contract.yaml": "allow",
      "cat *": "allow",
      "echo *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "find *": "allow",
      "ls *": "allow",
      "grep *": "allow",
      "which *": "allow",
      "cd *": "allow",
      "diff *": "allow",
      "sha256sum *": "allow",
      "cp *": "deny",
      "mv *": "deny",
      "rm *": "deny",
      "mkdir *": "deny",
      "rmdir *": "deny",
      "sed -i '' *": "deny",
      "node *": "deny",
      "bun *": "deny",
      "npx *": "deny",
      "npm *": "deny",
      "python3 *": "deny",
    },
    safe_delete: {
      "contract.yaml": "allow",
      ".opencode/state/machine.json": "allow",
      ".opencode/context/**": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      "opencode.json": "deny",
      ".opencode/state/**": "deny",
      ".opencode/project.config.json": "deny",
      "PROJECT_REFERENCE.md": "deny",
      ".opencode/rules/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/legacy/subagent-preamble.md": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/plugins/**": "deny",
      ".opencode/**": "deny",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "booking_system_refactor/booking-backend/test/**": "deny",
    },
    safe_mkdir: {
      ".opencode/context/**": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      "contract.yaml": "deny",
      ".opencode/state/machine.json": "deny",
      "opencode.json": "deny",
      ".opencode/state/**": "deny",
      ".opencode/project.config.json": "deny",
      "PROJECT_REFERENCE.md": "deny",
      ".opencode/rules/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/legacy/subagent-preamble.md": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/plugins/**": "deny",
      ".opencode/**": "deny",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "booking_system_refactor/booking-backend/test/**": "deny",
    },
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      "contract.yaml": "allow",
      ".opencode/state/machine.json": "allow",
      ".opencode/context/**": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      "opencode.json": "deny",
      ".opencode/state/**": "deny",
      ".opencode/project.config.json": "deny",
      "PROJECT_REFERENCE.md": "deny",
      ".opencode/rules/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/legacy/subagent-preamble.md": "deny",
      ".opencode/scripts/**": "deny",
      ".opencode/plugins/**": "deny",
      ".opencode/**": "deny",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "booking_system_refactor/booking-backend/test/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  "Coder-BE": {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    edit: "deny",
    glob: "allow",
    grep: "allow",
    bash: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    safe_edit: {
      "booking_system_refactor/booking-backend/src/**": "allow",
      "booking_system_refactor/booking-backend/test/**": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      "booking_system_refactor/booking-backend/*.json": "allow",
      "booking_system_refactor/booking-backend/*.js": "allow",
      "booking_system_refactor/booking-backend/*.ts": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-frontend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    safe_shell: {
      "which *": "allow",
      "npx tsc *": "allow",
      "tsc *": "allow",
      "echo *": "allow",
      "node *": "allow",
      "bun *": "allow",
      "npx *": "allow",
      "npm *": "allow",
      "grep *": "allow",
      "cat *": "allow",
      "wc *": "allow",
      "ls *": "allow",
      "find *": "allow",
      "cd *": "allow",
      "mkdir *": "allow",
      "sha256sum *": "allow",
      "rm -rf *": "ask",
    },
    safe_test: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    docker: "allow",
    postgre_sql: "allow",
    eslint_audit: "allow",
    code_quality_check: "allow",
    safe_diff: "allow",
    safe_delete: {
      "booking_system_refactor/booking-backend/src/**": "allow",
      "booking_system_refactor/booking-backend/test/**": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      "booking_system_refactor/booking-backend/*.json": "allow",
      "booking_system_refactor/booking-backend/*.js": "allow",
      "booking_system_refactor/booking-backend/*.ts": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-frontend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    safe_mkdir: {
      "booking_system_refactor/booking-backend/src/**": "allow",
      "booking_system_refactor/booking-backend/test/**": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      "booking_system_refactor/booking-backend/*.json": "allow",
      "booking_system_refactor/booking-backend/*.js": "allow",
      "booking_system_refactor/booking-backend/*.ts": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-frontend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      "booking_system_refactor/booking-backend/src/**": "allow",
      "booking_system_refactor/booking-backend/test/**": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      "booking_system_refactor/booking-backend/*.json": "allow",
      "booking_system_refactor/booking-backend/*.js": "allow",
      "booking_system_refactor/booking-backend/*.ts": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-frontend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  "Coder-FE": {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    edit: "deny",
    glob: "allow",
    grep: "allow",
    bash: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    safe_edit: {
      "booking_system_refactor/booking-frontend/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    safe_shell: {
      "which *": "allow",
      "npx tsc *": "allow",
      "tsc *": "allow",
      "echo *": "allow",
      "node *": "allow",
      "bun *": "allow",
      "npx *": "allow",
      "npm *": "allow",
      "grep *": "allow",
      "cat *": "allow",
      "wc *": "allow",
      "ls *": "allow",
      "find *": "allow",
      "cd *": "allow",
      "mkdir *": "allow",
      "sha256sum *": "allow",
      "rm -rf *": "ask",
    },
    safe_test: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    playwright: "allow",
    eslint_audit: "allow",
    code_quality_check: "allow",
    safe_diff: "allow",
    safe_delete: {
      "booking_system_refactor/booking-frontend/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    safe_mkdir: {
      "booking_system_refactor/booking-frontend/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      "booking_system_refactor/booking-frontend/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/**": "deny",
      "contract.yaml": "deny",
      "opencode.json": "deny",
      ".opencode/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  Guardian: {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    bash: "deny",
    edit: "deny",
    webfetch: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    eslint_audit: "allow",
    code_quality_check: "allow",
    safe_diff: "allow",
    safe_test: "allow",
    safe_edit: {
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/state/machine.json": "allow",
      ".opencode/state/gate-state.json": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/**": "deny",
      "AGENTS.md": "deny",
      "PROJECT_REFERENCE.md": "deny",
    },
    safe_shell: {
      "grep *": "allow",
      "git log*": "allow",
      "find *": "allow",
      "ls *": "allow",
      "sha256sum *": "allow",
    },
    safe_delete: {
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/state/machine.json": "allow",
      ".opencode/state/gate-state.json": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/**": "deny",
      "AGENTS.md": "deny",
      "PROJECT_REFERENCE.md": "deny",
    },
    safe_mkdir: {
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/state/machine.json": "allow",
      ".opencode/state/gate-state.json": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/**": "deny",
      "AGENTS.md": "deny",
      "PROJECT_REFERENCE.md": "deny",
    },
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/state/machine.json": "allow",
      ".opencode/state/gate-state.json": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/**": "deny",
      "AGENTS.md": "deny",
      "PROJECT_REFERENCE.md": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  Arbiter: {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    edit: "deny",
    bash: "deny",
    webfetch: "deny",
    safe_test: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    safe_diff: "allow",
    safe_edit: {
      ".task_temp/**": "allow",
      "WAIVE.md": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
    },
    safe_shell: {
      "cat *": "allow",
      "echo *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "find *": "allow",
      "ls *": "allow",
      "sha256sum *": "allow",
    },
    safe_delete: {
      ".task_temp/**": "allow",
      "WAIVE.md": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
    },
    safe_mkdir: {
      ".task_temp/**": "allow",
      "WAIVE.md": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
    },
    safe_restore: {
      ".task_temp/**": "allow",
      "WAIVE.md": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      "contract.yaml": "deny",
      ".opencode/tools/**": "deny",
      ".opencode/scripts/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  "CI-CD-Agent": {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    edit: "deny",
    bash: "deny",
    safe_shell: {
      "*": "allow",
      "sha256sum *": "allow",
      "gh *": "allow",
    },
    safe_test: "deny",
    webfetch: "deny",
    websearch: "deny",
    context7: "deny",
    dispatch_subagent: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    docker: "allow",
    github: "allow",
    safe_diff: "allow",
    safe_edit: {
      "docker-compose*.yml": "allow",
      ".github/workflows/**": "allow",
      "Dockerfile*": "allow",
      ".env.*": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      ".task_temp/**": "allow",
      ".opencode/state/gate-state.history/**": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/state/gate-state.archive.json": "allow",
      ".opencode/logs/archive/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/rules/**": "deny",
    },
    safe_delete: {
      "docker-compose*.yml": "allow",
      ".github/workflows/**": "allow",
      "Dockerfile*": "allow",
      ".env.*": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      ".task_temp/**": "allow",
      ".opencode/state/gate-state.history/**": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/state/gate-state.archive.json": "allow",
      ".opencode/logs/archive/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/rules/**": "deny",
    },
    safe_mkdir: {
      "docker-compose*.yml": "allow",
      ".github/workflows/**": "allow",
      "Dockerfile*": "allow",
      ".env.*": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      ".task_temp/**": "allow",
      ".opencode/state/gate-state.history/**": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/state/gate-state.archive.json": "allow",
      ".opencode/logs/archive/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/rules/**": "deny",
    },
    safe_restore: {
      "docker-compose*.yml": "allow",
      ".github/workflows/**": "allow",
      "Dockerfile*": "allow",
      ".env.*": "allow",
      "booking_system_refactor/booking-backend/prisma/**": "allow",
      ".task_temp/**": "allow",
      ".opencode/state/gate-state.history/**": "allow",
      ".opencode/state/gate-state.index.json": "allow",
      ".opencode/state/gate-state.archive.json": "allow",
      ".opencode/logs/archive/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
      ".opencode/agents/**": "deny",
      ".opencode/rules/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  "Knowledge-Curator": {
    task: "deny",
    read: "allow",
    question: "allow",
    glob: "allow",
    grep: "allow",
    edit: "deny",
    bash: "deny",
    webfetch: "allow",
    websearch: "allow",
    context7: "allow",
    skill: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    safe_edit: {
      "docs/official_docs/**": "allow",
      "docs/official_docs/.metadata/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/**": "deny",
      ".opencode/**": "deny",
    },
    safe_shell: {
      "mkdir *docs/official_docs*": "allow",
      "node .opencode/scripts/knowledge/*": "allow",
      "bun .opencode/scripts/knowledge/*": "allow",
      "npm run *": "allow",
      "sha256sum *": "allow",
      "cp *": "allow",
      "mv *": "allow",
      "echo *": "allow",
      "which *": "allow",
      "ls *": "allow",
      "cat *": "allow",
      "find *": "allow",
      "grep *": "allow",
      "wc *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "cd *": "allow",
    },
    safe_mkdir: {
      "docs/official_docs/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/**": "deny",
      ".opencode/**": "deny",
    },
    safe_delete: {
      "docs/official_docs/**": "allow",
      "docs/official_docs/.metadata/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/**": "deny",
      ".opencode/**": "deny",
    },
    safe_diff: {
      "docs/official_docs/**": "allow",
    } as any,
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    safe_restore: {
      "docs/official_docs/**": "allow",
      "docs/official_docs/.metadata/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/**": "deny",
      ".opencode/**": "deny",
    },
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
  "Super-Admin": {
    task: {
      "*": "deny",
      "Knowledge-Curator": "allow",
      explore: "allow",
    },
    read: "allow",
    question: "allow",
    glob: "allow",
    github: "allow",
    grep: "allow",
    edit: "deny",
    bash: "deny",
    webfetch: "deny",
    websearch: "deny",
    safe_test: "deny",
    context7: "deny",
    skill: "allow",
    pandoc: "allow",
    todowrite: "allow",
    resolve_domain_id: "allow",
    compliance_gate_check: "allow",
    compliance_gate_confirm: "allow",
    compliance_gate_complete: "allow",
    checklist_status: "allow",
    advance_checklist_phase: "allow",
    code_quality_check: "allow",
    safe_diff: "allow",
    safe_restore: {
      ".opencode/**": "allow",
      "opencode.json": "allow",
      "AGENTS.md": "allow",
      "PROJECT_REFERENCE.md": "allow",
      "contract.yaml": "allow",
      "Task.DAG.json": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
    },
    safe_edit: {
      ".opencode/**": "allow",
      "opencode.json": "allow",
      "AGENTS.md": "allow",
      "PROJECT_REFERENCE.md": "allow",
      "contract.yaml": "allow",
      "Task.DAG.json": "allow",
      "TECH_DEBT_REGISTRY.md": "allow",
      "WAIVE.md": "allow",
      ".task_temp/**": "allow",
      "docs/**": "allow",
      ".github/workflows/**": "allow",
      "gh-workflow/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
    },
    safe_shell: {
      "*": "allow",
      "cat *": "allow",
      "echo *": "allow",
      "head *": "allow",
      "tail *": "allow",
      "wc *": "allow",
      "find *": "allow",
      "ls *": "allow",
      "cp *": "allow",
      "mv *": "allow",
      "rm *": "allow",
      "mkdir *": "allow",
      "rmdir *": "allow",
      "sed -i *": "allow",
      "node *": "allow",
      "bun *": "allow",
      "node .opencode/scripts/*": "allow",
      "bun .opencode/scripts/*": "allow",
      "npx *": "allow",
      "npm *": "allow",
      "grep *": "allow",
      "which *": "allow",
      "cd *": "allow",
      "diff *": "allow",
      "python3 *": "allow",
      "git *": "allow",
      "sha256sum *": "allow",
    },
    safe_delete: {
      ".opencode/**": "allow",
      "opencode.json": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
    },
    safe_mkdir: {
      ".opencode/**": "allow",
      ".task_temp/**": "allow",
      "booking_system_refactor/booking-backend/src/**": "deny",
      "booking_system_refactor/booking-frontend/src/**": "deny",
    },
    dispatch_subagent: "allow",
    safe_hash: "allow",
    codegraph_query: "allow",
    codegraph_explore: "allow",
    codegraph_callers: "allow",
    codegraph_callees: "allow",
    codegraph_node: "allow",
    codegraph_status: "allow",
    codegraph_files: "allow",
    acp_notify: "allow",
    config_read_attest: "allow",
    skill_read_attest: "allow",
    rule_read_attest: "allow",
  } as AgentPermission,
};
