'use strict';

/**
 * ESLint plugin: opencode-mock-audit
 * 
 * Rules derive their TIER service lists from contract.yaml via tier-rules.json.
 * tier-rules.json is auto-generated by the MCP tool eslint-audit.js before each run.
 * 
 * CAT1.x = Architecture (error, blocks commit/gate)
 * CAT2.x = Security    (error, blocks commit/gate)
 * CAT3.x = Quality     (warn,  flags in review)
 * CAT4.x = Architecture Quality (warn, architecture guidance)
 * 
 * All 11 rules are registered below. Rules without require() paths are not active.
 */
module.exports = {
  rules: {
    // CAT1: Architecture
    'no-tier1-mock': require('./rules/no-tier1-mock'),
    'no-skipped-tests': require('./rules/no-skipped-tests'),
    'no-skipped-audit': require('./rules/no-skipped-audit'),
    
    // CAT2: Security
    'no-console-log': require('./rules/no-console-log'),
    
    // CAT3: Quality
    'tier3-verify': require('./rules/tier3-verify'),
    'no-uncovered-switch': require('./rules/no-uncovered-switch'),
    'no-empty-assertions': require('./rules/no-empty-assertions'),
    'no-only-left': require('./rules/no-only-left'),
    'no-any-in-spec': require('./rules/no-any-in-spec'),
    'max-complexity-enforce': require('./rules/max-complexity-enforce'),
    
    // CAT4: Architecture Quality
    'no-deep-import': require('./rules/no-deep-import'),
  },
};
