// task-before.ts — "tool.execute.before" plugin: DISPATCH-INTEGRITY validation
// =======================================================================
// Intercepts Task() tool calls and validates that the prompt contains a
// DISPATCH_TOKEN hash, proving it was generated by dispatch_subagent().
//
// BUG 1 FIX v2 (2026-06-18, @Super-Admin): Upgraded from existence-only check
// to SHA-256 integrity hash verification. Prevents agents from faking
// DISPATCH_TOKEN with any random hex string — token must match
// sha256(cleanPrompt) where cleanPrompt is the prompt without the token line.
//
// v1: dispatch_subagent generates wrapped prompt with DISPATCH_TOKEN + P0
//     protocol + scope boundary. Task() before-hook verifies token EXISTS.
// v2: before-hook extracts token, strips DISPATCH_TOKEN line, re-hashes
//     cleanPrompt, and compares. Any modification between dispatch_subagent
//     output and Task() invocation causes a hash mismatch.
//
// Enforcement:
//   strict/locked → throw [FW-ENFORCE][DISPATCH-INTEGRITY] if token missing OR hash mismatch
//   advisory      → log WARNING, allow through
//
// @author @Super-Admin (framework repair — dispatch-gap-bug.md Bug 1)
// @since 2026-06-18

import { writeLog } from "../lib/log-manager";
import { withPluginLifecycle } from "../lib/hook-lifecycle";
import { getEnforcementMode } from "../lib/gate-core";
import { resolveAgent } from "../lib/agent-resolver";

export default withPluginLifecycle("task-before", {
  "tool.execute.before": taskExecuteBefore,
});

/**
 * Validates that Task() prompts contain a DISPATCH_TOKEN, ensuring all
 * sub-agent dispatches go through dispatch_subagent() first.
 *
 * Why: Without this check, agents can bypass the P0 protocol (compliance
 * gate, UC7KS pipeline, scope boundary) by manually writing Task() prompts.
 */
async function taskExecuteBefore(input: any, output: any): Promise<void> {
  // Only intercept Task() dispatch calls (tool name may be "task" or "Task")
  const isTask = input.tool === "task" || input.tool === "Task";
  if (!isTask) return;

  const agent = resolveAgent(input.sessionID) || "unknown";
  let prompt = output?.args?.prompt || "";
  const mode = getEnforcementMode();

  // ── LLM-FREE BRIDGE: Auto-dispatch marker (QUEUE-BASED v2) ──
  // When dispatch_subagent writes .auto-dispatch.json, the LLM receives a
  // short confirmation instead of the full wrapped prompt. task-before
  // reads the full prompt from the dispatch file and replaces the
  // LLM-provided prompt with the original, ensuring DISPATCH_TOKEN
  // hash verification succeeds.
  //
  // FIX v2 (2026-06-19, @Super-Admin, SA-REVIEW-AUTO-DISPATCH-BUG):
  // Changed from single-entry read-and-delete to FIFO queue dequeue.
  // Now matches the correct entry by subagent_type + sessionId instead of
  // blindly consuming whichever entry happens to be in the file.
  // Agent-type mismatch is logged and blocked in strict/locked mode.
  const root = process.env.OPENCODE_ROOT || process.cwd();
  const dispatchDir = root + "/.task_temp/_dispatch";
  const queuePath = dispatchDir + "/.auto-dispatch.json";
  const legacyPath = dispatchDir + "/.auto-dispatch";
  const subagentType = output?.args?.subagent_type || "";

  // Check queue file first, then legacy
  const markerPath = require("node:fs").existsSync(queuePath)
    ? queuePath
    : require("node:fs").existsSync(legacyPath)
      ? legacyPath
      : null;

  if (markerPath) {
    try {
      const raw = require("node:fs").readFileSync(markerPath, "utf8");
      let queue = JSON.parse(raw);

      // Normalize: single entry → wrap in array (legacy compat)
      if (!Array.isArray(queue)) {
        queue = [queue];
      }

      /** Queue entry for auto-dispatch marker */
      interface AutoDispatchEntry {
        sessionId: string;
        agentType: string;
        taskId: string;
        filePath: string;
        createdAt: number;
      }
      let entry: AutoDispatchEntry | null = null;
      let matchQuality = "";

      // Strategy 1: Exact match by agentType + sessionId
      for (let i = 0; i < queue.length; i++) {
        if (
          queue[i].agentType === subagentType &&
          queue[i].sessionId === input.sessionID
        ) {
          entry = queue.splice(i, 1)[0];
          matchQuality = "exact (agentType+sessionId)";
          break;
        }
      }

      // Strategy 2: Match by agentType only (cross-session)
      if (!entry) {
        for (let i = 0; i < queue.length; i++) {
          if (queue[i].agentType === subagentType) {
            entry = queue.splice(i, 1)[0];
            matchQuality = "agentType-only (session mismatch)";
            writeLog("task-before", "runtime", {
              sessionID: input.sessionID,
              callID: input.callID,
              agent,
              agentType: agent,
              level: "WARN",
              event: "AUTO-DISPATCH-SESSION-MISMATCH",
              detail: `Matched by agentType only. Marker sessionId=${entry.sessionId} != current=${input.sessionID}`,
            });
            break;
          }
        }
      }

      // Strategy 3: Take oldest entry (last resort — agent mismatch)
      if (!entry && queue.length > 0) {
        entry = queue.shift()!;
        matchQuality = "fallback-oldest (agent MISMATCH)";
        writeLog("task-before", "runtime", {
          sessionID: input.sessionID,
          callID: input.callID,
          agent,
          agentType: agent,
          level: "ERROR",
          event: "AUTO-DISPATCH-AGENT-MISMATCH",
          detail: `No matching entry for ${subagentType}. Used oldest: ${entry.agentType}:${entry.taskId} from session ${entry.sessionId}`,
        });

        // Block agent-type mismatch in strict/locked mode
        if (
          (mode === "strict" || mode === "locked") &&
          entry.agentType !== subagentType
        ) {
          throw new Error(
            `[FW-ENFORCE][AUTO-DISPATCH-AGENT-MISMATCH] ` +
              `Task() subagent_type="${subagentType}" but marker is for "${entry.agentType}". ` +
              `This means the auto-dispatch marker queue is out of sync — ` +
              `the wrong agent's prompt would be loaded. ` +
              `Re-dispatch with matching agent_type.`,
          );
        }
      }

      if (entry) {
        const fullPrompt = require("node:fs").readFileSync(
          entry.filePath,
          "utf8",
        );
        if (fullPrompt) {
          prompt = fullPrompt;
          if (output?.args) {
            output.args.prompt = fullPrompt;
          }
          writeLog("task-before", "runtime", {
            sessionID: input.sessionID,
            callID: input.callID,
            agent,
            agentType: agent,
            event: "AUTO-DISPATCH-CONSUMED",
            detail: `Loaded full prompt (${fullPrompt.length} bytes) from ${entry.filePath} | match=${matchQuality} | queue=${queue.length} remaining`,
          });
        }

        // Write back remaining queue or delete if empty
        if (markerPath === legacyPath || queue.length === 0) {
          try {
            require("node:fs").unlinkSync(markerPath);
          } catch {}
        } else {
          try {
            require("node:fs").writeFileSync(
              markerPath,
              JSON.stringify(queue),
              "utf8",
            );
          } catch {}
        }
      }
    } catch (e: any) {
      // Rethrow enforcement errors
      if (e.message && e.message.includes("[FW-ENFORCE]")) throw e;
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "AUTO-DISPATCH-FAILED",
        detail: `Cannot load dispatch file from marker: ${e.message}`,
      });
    }
  }

  // DISPATCH-INTEGRITY v2: Extract token, strip line, verify hash.
  // Upgraded from existence-only check to SHA-256 integrity verification.
  // DISPATCH_TOKEN is a SHA-256 hash of the clean prompt (without the token line),
  // injected by dispatch_subagent.ts. Any modification to the prompt between
  // dispatch_subagent output and Task() invocation will cause a hash mismatch.
  const tokenMatch = prompt.match(/\/\/DISPATCH_TOKEN:([a-f0-9]{64})/);

  if (!tokenMatch) {
    if (mode === "strict" || mode === "locked") {
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "TOOL-BEFORE",
        detail:
          "BLOCKED | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN" +
          ` | subagent_type=${output?.args?.subagent_type || "?"}`,
      });
      throw new Error(
        "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() prompt missing DISPATCH_TOKEN. " +
          "All sub-agent dispatches MUST go through dispatch_subagent() first. " +
          "Re-dispatch using: dispatch_subagent(agent_type, task_description, dag_task_id) " +
          "→ Task({prompt: <wrapped output>})",
      );
    }

    // Advisory mode: log warning but allow
    writeLog("task-before", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      agent,
      agentType: agent,
      level: "WARN",
      event: "TOOL-BEFORE",
      detail:
        "WARN | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN (advisory, allowed)" +
        ` | subagent_type=${output?.args?.subagent_type || "?"}`,
    });
    return;
  }

  const token = tokenMatch[1];

  // Strip DISPATCH_TOKEN line to recover clean prompt, then verify integrity.
  // The clean prompt is what dispatch_subagent.ts hashed to produce the token.
  const cleanPrompt = prompt
    .replace(/\/\/DISPATCH_TOKEN:[a-f0-9]{64}\s*$/, "")
    .replace(/\n+$/, "");
  const expectedHash = require("crypto")
    .createHash("sha256")
    .update(cleanPrompt)
    .digest("hex");

  if (token !== expectedHash) {
    // Hash mismatch: prompt was modified after dispatch_subagent generation.
    // This means the agent did NOT pass the wrapped prompt verbatim to Task().
    if (mode === "strict" || mode === "locked") {
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "DISPATCH-INTEGRITY-HASH-MISMATCH",
        detail:
          "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() DISPATCH_TOKEN hash mismatch" +
          ` | expected=${expectedHash.slice(0, 16)}...` +
          ` | got=${token.slice(0, 16)}...` +
          ` | subagent_type=${output?.args?.subagent_type || "?"}`,
      });
      throw new Error(
        "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() prompt tampered — DISPATCH_TOKEN hash mismatch. " +
          "Prompt must be used verbatim from dispatch_subagent output.",
      );
    }

    // Advisory mode: log warning but allow
    writeLog("task-before", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      agent,
      agentType: agent,
      level: "WARN",
      event: "TOOL-BEFORE",
      detail:
        "WARN | DISPATCH-INTEGRITY | Task() DISPATCH_TOKEN hash mismatch (advisory, allowed)" +
        ` | expected=${expectedHash.slice(0, 16)}...` +
        ` | got=${token.slice(0, 16)}...` +
        ` | subagent_type=${output?.args?.subagent_type || "?"}`,
    });
    return;
  }

  // Token present and hash verified — log pass
  writeLog("task-before", "runtime", {
    sessionID: input.sessionID,
    callID: input.callID,
    agent,
    agentType: agent,
    event: "TOOL-BEFORE",
    detail:
      "pass | DISPATCH-INTEGRITY hash verified" +
      ` | subagent_type=${output?.args?.subagent_type || "?"}`,
  });
}
