// task-before.ts — "tool.execute.before" plugin: DISPATCH-INTEGRITY validation
// =======================================================================
// Intercepts Task() tool calls and validates that the prompt contains a
// DISPATCH_TOKEN hash, proving it was generated by dispatch_subagent().
//
// BUG 1 FIX v2 (2026-06-18, @Super-Admin): Upgraded from existence-only check
// to SHA-256 integrity hash verification. Prevents agents from faking
// DISPATCH_TOKEN with any random hex string — token must match
// sha256(cleanPrompt) where cleanPrompt is the prompt without the token line.
//
// v1: dispatch_subagent generates wrapped prompt with DISPATCH_TOKEN + P0
//     protocol + scope boundary. Task() before-hook verifies token EXISTS.
// v2: before-hook extracts token, strips DISPATCH_TOKEN line, re-hashes
//     cleanPrompt, and compares. Any modification between dispatch_subagent
//     output and Task() invocation causes a hash mismatch.
//
// Enforcement:
//   strict/locked → throw [FW-ENFORCE][DISPATCH-INTEGRITY] if token missing OR hash mismatch
//   advisory      → log WARNING, allow through
//
// @author @Super-Admin (framework repair — dispatch-gap-bug.md Bug 1)
// @since 2026-06-18

import { writeLog } from "../lib/log-manager";
import { withPluginLifecycle } from "../lib/hook-lifecycle";
import { getEnforcementMode } from "../lib/gate-core";
import { resolveAgent } from "../lib/agent-resolver";

export default withPluginLifecycle("task-before", {
  "tool.execute.before": taskExecuteBefore,
});

/**
 * Validates that Task() prompts contain a DISPATCH_TOKEN, ensuring all
 * sub-agent dispatches go through dispatch_subagent() first.
 *
 * Why: Without this check, agents can bypass the P0 protocol (compliance
 * gate, UC7KS pipeline, scope boundary) by manually writing Task() prompts.
 */
async function taskExecuteBefore(input: any, output: any): Promise<void> {
  // Only intercept Task() dispatch calls (tool name may be "task" or "Task")
  const isTask = input.tool === "task" || input.tool === "Task";
  if (!isTask) return;

  const agent = resolveAgent(input.sessionID) || "unknown";
  const prompt = output?.args?.prompt || "";
  const mode = getEnforcementMode();

  // DISPATCH-INTEGRITY v2: Extract token, strip line, verify hash.
  // Upgraded from existence-only check to SHA-256 integrity verification.
  // DISPATCH_TOKEN is a SHA-256 hash of the clean prompt (without the token line),
  // injected by dispatch_subagent.ts. Any modification to the prompt between
  // dispatch_subagent output and Task() invocation will cause a hash mismatch.
  const tokenMatch = prompt.match(/\/\/DISPATCH_TOKEN:([a-f0-9]{64})/);

  if (!tokenMatch) {
    if (mode === "strict" || mode === "locked") {
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "TOOL-BEFORE",
        detail:
          "BLOCKED | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN" +
          ` | subagent_type=${output?.args?.subagent_type || "?"}`,
      });
      throw new Error(
        "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() prompt missing DISPATCH_TOKEN. " +
          "All sub-agent dispatches MUST go through dispatch_subagent() first. " +
          "Re-dispatch using: dispatch_subagent(agent_type, task_description, dag_task_id) " +
          "→ Task({prompt: <wrapped output>})",
      );
    }

    // Advisory mode: log warning but allow
    writeLog("task-before", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      agent,
      agentType: agent,
      level: "WARN",
      event: "TOOL-BEFORE",
      detail:
        "WARN | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN (advisory, allowed)" +
        ` | subagent_type=${output?.args?.subagent_type || "?"}`,
    });
    return;
  }

  const token = tokenMatch[1];

  // Strip DISPATCH_TOKEN line to recover clean prompt, then verify integrity.
  // The clean prompt is what dispatch_subagent.ts hashed to produce the token.
  const cleanPrompt = prompt.replace(/\/\/DISPATCH_TOKEN:[a-f0-9]{64}\s*$/, "");
  const expectedHash = require("crypto")
    .createHash("sha256")
    .update(cleanPrompt)
    .digest("hex");

  if (token !== expectedHash) {
    // Hash mismatch: prompt was modified after dispatch_subagent generation.
    // This means the agent did NOT pass the wrapped prompt verbatim to Task().
    if (mode === "strict" || mode === "locked") {
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "TOOL-BEFORE",
        detail:
          "BLOCKED | DISPATCH-INTEGRITY | Task() DISPATCH_TOKEN hash mismatch" +
          ` | expected=${expectedHash.slice(0, 16)}...` +
          ` | got=${token.slice(0, 16)}...` +
          ` | subagent_type=${output?.args?.subagent_type || "?"}`,
      });
      throw new Error(
        "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() prompt tampered — DISPATCH_TOKEN hash mismatch. " +
          "Prompt must be used verbatim from dispatch_subagent output.",
      );
    }

    // Advisory mode: log warning but allow
    writeLog("task-before", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      agent,
      agentType: agent,
      level: "WARN",
      event: "TOOL-BEFORE",
      detail:
        "WARN | DISPATCH-INTEGRITY | Task() DISPATCH_TOKEN hash mismatch (advisory, allowed)" +
        ` | expected=${expectedHash.slice(0, 16)}...` +
        ` | got=${token.slice(0, 16)}...` +
        ` | subagent_type=${output?.args?.subagent_type || "?"}`,
    });
    return;
  }

  // Token present and hash verified — log pass
  writeLog("task-before", "runtime", {
    sessionID: input.sessionID,
    callID: input.callID,
    agent,
    agentType: agent,
    event: "TOOL-BEFORE",
    detail:
      "pass | DISPATCH-INTEGRITY hash verified" +
      ` | subagent_type=${output?.args?.subagent_type || "?"}`,
  });
}
