// task-before.ts — "tool.execute.before" plugin: DISPATCH-INTEGRITY validation
// =======================================================================
// Intercepts Task() tool calls and validates that the prompt contains a
// DISPATCH_TOKEN hash, proving it was generated by dispatch_subagent().
//
// BUG 1 FIX (2026-06-18): dispatch_subagent generates a wrapped prompt with
// DISPATCH_TOKEN + P0 protocol + scope boundary, but Task() had no before-hook
// to verify the prompt actually came from dispatch_subagent. Agents could
// manually write simplified prompts, bypassing the P0 protocol entirely.
//
// Enforcement:
//   strict/locked → throw [FW-ENFORCE][DISPATCH-INTEGRITY] if token missing
//   advisory      → log WARNING, allow through
//
// @author @Super-Admin (framework repair — dispatch-gap-bug.md Bug 1)
// @since 2026-06-18

import { writeLog } from "../lib/log-manager";
import { withPluginLifecycle } from "../lib/hook-lifecycle";
import { getEnforcementMode } from "../lib/gate-core";
import { resolveAgent } from "../lib/agent-resolver";

export default withPluginLifecycle("task-before", {
  "tool.execute.before": taskExecuteBefore,
});

/**
 * Validates that Task() prompts contain a DISPATCH_TOKEN, ensuring all
 * sub-agent dispatches go through dispatch_subagent() first.
 *
 * Why: Without this check, agents can bypass the P0 protocol (compliance
 * gate, UC7KS pipeline, scope boundary) by manually writing Task() prompts.
 */
async function taskExecuteBefore(input: any, output: any): Promise<void> {
  // Only intercept Task() dispatch calls (tool name may be "task" or "Task")
  const isTask = input.tool === "task" || input.tool === "Task";
  if (!isTask) return;

  const agent = resolveAgent(input.sessionID) || "unknown";
  const prompt = output?.args?.prompt || "";
  const mode = getEnforcementMode();

  // DISPATCH_TOKEN is a SHA-256 hash injected by dispatch_subagent.ts
  const hasToken = /DISPATCH_TOKEN:[a-f0-9]{64}/.test(prompt);

  if (!hasToken) {
    if (mode === "strict" || mode === "locked") {
      writeLog("task-before", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agentType: agent,
        level: "ERROR",
        event: "TOOL-BEFORE",
        detail:
          "BLOCKED | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN" +
          ` | subagent_type=${output?.args?.subagent_type || "?"}`,
      });
      throw new Error(
        "[FW-ENFORCE][DISPATCH-INTEGRITY] Task() prompt missing DISPATCH_TOKEN. " +
          "All sub-agent dispatches MUST go through dispatch_subagent() first. " +
          "Re-dispatch using: dispatch_subagent(agent_type, task_description, dag_task_id) " +
          "→ Task({prompt: <wrapped output>})",
      );
    }

    // Advisory mode: log warning but allow
    writeLog("task-before", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      agent,
      agentType: agent,
      level: "WARN",
      event: "TOOL-BEFORE",
      detail:
        "WARN | DISPATCH-INTEGRITY | Task() prompt missing DISPATCH_TOKEN (advisory, allowed)" +
        ` | subagent_type=${output?.args?.subagent_type || "?"}`,
    });
    return;
  }

  // Token present — log pass
  writeLog("task-before", "runtime", {
    sessionID: input.sessionID,
    callID: input.callID,
    agent,
    agentType: agent,
    event: "TOOL-BEFORE",
    detail:
      "pass | DISPATCH-INTEGRITY verified" +
      ` | subagent_type=${output?.args?.subagent_type || "?"}`,
  });
}
