// task-after.ts — "tool.execute.after" plugin: task failure recording
import * as fs from "node:fs";
import * as path from "node:path";
import { writeLog } from "../lib/log-manager";
import { withPluginLifecycle } from "../lib/hook-lifecycle";
import { resolveAgent, resolveTaskId } from "../lib/agent-resolver";
import { capFailedEntries, atomicWriteJson } from "../lib/state-utils";
import { findArmedSession } from "../lib/gate-core";
import {
  dbAppendSessionLog,
  dbAppendDispatchFailed,
} from "../lib/db-state-manager";

const FAILED_FILE = ".task_temp/_dispatch/.pending.json.failed";
const GATE_REMINDER_FILE = ".task_temp/_global/gate-reminder.md";

export default withPluginLifecycle("task-after", {
  "tool.execute.after": toolExecuteAfter,
  // Point 3b of compliance-gate-optimization-plan.md:
  // push armed gate reminder into the compaction context so it survives
  // context compression. Only fires during experimental.session.compacting.
  "experimental.session.compacting": compactionHook,
});

async function toolExecuteAfter(input: any, output: any): Promise<void> {
  // Only track Task() dispatch calls
  const isTask = input.tool === "Task" || input.tool === "task";
  if (!isTask) return;

  const agent = resolveAgent(input.sessionID);
  const taskId = resolveTaskId(input.sessionID);

  // Record dispatch outcome
  const outcome = output?.error || output?.failed ? "FAILURE" : "SUCCESS";

  writeLog("task-after", "runtime", {
    sessionID: input.sessionID,
    callID: input.callID,
    agent,
    agent,
    event: "TOOL-AFTER",
    detail: `dispatch-outcome | status=${outcome} | taskId=${taskId} | agentType=${input.args?.subagent_type || "?"}`,
  });

  // On failure, record to dispatch_failed_log DB (replaces .pending.json.failed)
  if (outcome === "FAILURE") {
    try {
      dbAppendDispatchFailed({
        dispatchId: input.callID || "unknown",
        agentType: input.args?.subagent_type || "unknown",
        dagTaskId: taskId || undefined,
        sessionId: input.sessionID,
        createdAt: Date.now(),
        failedAt: Date.now(),
        reason: "task-failure",
        errorMsg: (output?.error || output?.failed || "unknown").toString(),
      });
    } catch (err: any) {
      writeLog("task-after", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        agent,
        level: "ERROR",
        event: "TOOL-AFTER",
        detail: "failure-record failed: " + err.message,
      });
    }
  }

  // ── Point 3a: Armed gate fallback reminder ───────────────────────────────
  // When a Task() dispatch completes successfully and the gate is still
  // armed, write a persistent reminder file. This is the FALLBACK mechanism
  // for Point 3 of compliance-gate-optimization-plan.md (the PRIMARY
  // mechanism is the reminder text appended to the check/confirm MCP
  // response, which lives in the LLM's conversation context). The file
  // persists across context compressions and agent switches so any
  // subsequent agent (or the user) can see that compliance_gate_complete
  // still needs to be called.
  //
  // NOTE: `tui.prompt.append` is listed as a TUI event in the OpenCode
  // plugin docs but has no documented programmatic API for plugins to
  // emit. We rely on `client.app.log` (via writeLog) + file persistence
  // instead. See compliance-gate-optimization-plan.md §3 for the
  // feasibility analysis.
  if (outcome === "SUCCESS") {
    try {
      const armed = findArmedSession();
      if (armed.found && armed.gateSessionId) {
        const root = process.env.OPENCODE_ROOT || ".";
        const rf = path.join(root, GATE_REMINDER_FILE);
        const dir = path.dirname(rf);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        const dispatchedAgent = input.args?.subagent_type || agent || "unknown";
        const ts = new Date().toISOString();

        // Atomic write helper: write to .tmp, then rename over the target.
        // Keeps the reminder files consistent even if multiple Task() calls
        // fire close together.
        const atomicWriteText = (target: string, text: string): void => {
          const tmp = `${target}.tmp.${process.pid}`;
          fs.writeFileSync(tmp, text, "utf8");
          fs.renameSync(tmp, target);
        };

        // 1) Human-readable markdown reminder (the primary file)
        const mdContent =
          "# Gate Reminder (auto-generated by task-after.ts)\n\n" +
          "- **Status**: gate session `" +
          armed.gateSessionId +
          "` is still ARMED\n" +
          "- **Last dispatch**: `" +
          dispatchedAgent +
          "` completed task `" +
          (taskId || "(none)") +
          "` at " +
          ts +
          "\n" +
          "- **Required action**: call `compliance_gate_complete` with\n" +
          "  ```json\n" +
          '  { "session_id": "' +
          armed.gateSessionId +
          '", "execution_summary": "..." }\n' +
          "  ```\n" +
          "- **Why**: leaving the gate armed will block the next `git commit` via the pre-commit hook (Layer 0).\n";
        atomicWriteText(rf, mdContent);

        // 2) Machine-readable JSON sidecar (for downstream tooling)
        atomicWriteJson(rf.replace(/\.md$/, ".json"), {
          session_id: armed.gateSessionId,
          last_dispatched_agent: dispatchedAgent,
          last_task_id: taskId || null,
          written_at: ts,
          note: "This file is the Point 3 FALLBACK reminder. The PRIMARY reminder lives in the LLM conversation context (appended to the check/confirm MCP response).",
        });

        writeLog("task-after", "runtime", {
          sessionID: input.sessionID,
          callID: input.callID,
          agent,
          level: "WARN",
          event: "GATE-REMINDER-WRITTEN",
          detail: `armed session ${armed.gateSessionId} still open after dispatch of ${dispatchedAgent} — wrote ${GATE_REMINDER_FILE}`,
        });
      }
    } catch (err: any) {
      // Reminder generation is best-effort; never block dispatch
      writeLog("task-after", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        agent,
        level: "WARN",
        event: "GATE-REMINDER-FAILED",
        detail: "armed-session reminder skipped: " + err.message,
      });
    }

    // ── P6/S25-FIX-V4: Persist sub-agent session via DB ──
    // FIX HISTORY:
    //   v1: resolveTaskId() → FAIL (env var cleared by dispatch_subagent finally block)
    //   v2: promptHash bridge → FAIL (hash mismatch: 12KB dispatch output vs ~100-char
    //        Task() prompt argument — completely different content)
    //   v3: Keep FRAMEWORK_TASK_ID on parent process.env → FAIL (introduces Bug 2:
    //        env pollution → permanent DAG gate blocking if Task() never called)
    //   v4: Read .dispatch_ctx file → dbAppendSessionLog() → delete .dispatch_ctx.
    //   v5 (V1.3 Phase 2, 2026-06-23): .dispatch_ctx write removed. Read ctx/{dagTaskId}.json
    //        per-dispatch files instead (isolated, race-free).
    try {
      const subSessionId = output?.metadata?.sessionId;
      if (!subSessionId) return;

      const root = process.env.OPENCODE_ROOT || ".";
      let dagTaskId: string | null = null;

      // V1.3 Phase 2: Try per-dispatch ctx/ files first (isolated, race-free)
      try {
        const ctxDir = path.join(root, ".task_temp", "_dispatch", "ctx");
        if (fs.existsSync(ctxDir)) {
          const files = fs
            .readdirSync(ctxDir)
            .filter((f) => f.endsWith(".json"));
          if (files.length > 0) {
            const latest = files.reduce((a, b) => {
              const sa = fs.statSync(path.join(ctxDir, a));
              const sb = fs.statSync(path.join(ctxDir, b));
              return sa.mtimeMs > sb.mtimeMs ? a : b;
            });
            const ctx = JSON.parse(
              fs.readFileSync(path.join(ctxDir, latest), "utf8"),
            );
            dagTaskId = ctx.dagTaskId || null;
            // Clean up consumed per-dispatch file
            fs.unlinkSync(path.join(ctxDir, latest));
            writeLog("task-after", "runtime", {
              sessionID: input.sessionID,
              event: "DISPATCH-CTX-CLEANUP",
              detail: `Per-dispatch context cleaned: ctx/${latest}`,
            });
          }
        }
      } catch {
        // OPT-02 (2026-06-23): DB-canonical — per-dispatch ctx read failed.
        // Legacy .dispatch_ctx fallback removed; fall through to resolveTaskId().
      }

      // OPT-02 (2026-06-23): Legacy .dispatch_ctx cleanup removed.
      // All dispatch context is now in per-dispatch ctx/{dagTaskId}.json files.

      if (!dagTaskId) dagTaskId = resolveTaskId(input.sessionID);

      if (dagTaskId) {
        const subAgentType = input.args?.subagent_type || agent || "unknown";
        const runId = process.env.OPENCODE_RUN_ID || null;
        dbAppendSessionLog(subSessionId, dagTaskId, subAgentType, runId);
        writeLog("task-after", "runtime", {
          sessionID: input.sessionID,
          callID: input.callID,
          agent,
          agent,
          event: "SESSION-LOG-APPENDED",
          detail: `sub-agent sessionId=${subSessionId} dagTaskId=${dagTaskId} agentType=${subAgentType}`,
        });

        // ═══════════════════════════════════════════════════════════════
        // A7: DB-canonical dispatch consume (Phase 1).
        // After successful Task() dispatch, update the dispatch_queue
        // entry to 'consumed' by matching on dag_task_id and agent_type.
        // Also insert dispatch_context and dispatch_attempts records.
        //
        // Looks up the most recent 'running' entry with matching
        // dag_task_id + agent_type that matches this session's lease.
        // Non-fatal: failures logged but never block dispatch.
        // ═══════════════════════════════════════════════════════════════
        try {
          const {
            dbConsumeDispatch,
            dbInsertDispatchContext,
            dbInsertDispatchAttempt,
            dbGetDispatchQueue,
          } = require("../lib/dispatch-db");

          // Find the running entry for this dag_task_id + agent_type
          const runningEntries = dbGetDispatchQueue("running", subAgentType, 5);
          const match = runningEntries.find(
            (e: any) =>
              e.dag_task_id === dagTaskId &&
              (e.lease_owner === subSessionId ||
                e.lease_owner === input.sessionID),
          );

          if (match) {
            // Consume the dispatch
            dbConsumeDispatch(match.id, subSessionId);

            // OPT-06 (2026-06-24): dbInsertDispatchContext removed —
            // dispatch_context table is write-only (never read). session_map DB
            // is the canonical source for dispatch context. Table will be DROPPED in v23.

            // Insert attempt record
            dbInsertDispatchAttempt(match.id, 1, "success", subSessionId);

            writeLog("task-after", "runtime", {
              sessionID: input.sessionID,
              callID: input.callID,
              agent,
              agent,
              event: "DISPATCH-QUEUE-CONSUME",
              detail: `Consumed dispatch queueId=${match.id} dagTaskId=${dagTaskId} agentType=${subAgentType}`,
            });
          } else {
            // Entry not found in DB — may have been file-based dispatch.
            // Insert context + attempt without a queue_id reference.
            writeLog("task-after", "runtime", {
              sessionID: input.sessionID,
              callID: input.callID,
              agent,
              agent,
              event: "DISPATCH-QUEUE-CONSUME-NO-MATCH",
              detail: `No running DB entry for dagTaskId=${dagTaskId} agentType=${subAgentType} — file-based dispatch assumed`,
            });
          }
        } catch (e: any) {
          writeLog("task-after", "runtime", {
            sessionID: input.sessionID,
            callID: input.callID,
            agent,
            agent,
            level: "WARN",
            event: "DISPATCH-DB-CONSUME-FAILED",
            detail: `DB dispatch consume failed: ${e.message}. File-based fallback intact.`,
          });
        }
      }
    } catch {
      // Session log persistence is best-effort; never block dispatch
    }
  }
}

/**
 * Point 3b: push armed gate reminder into the compaction context.
 * Fires only when OpenCode triggers experimental.session.compacting.
 * This is the last-resort mechanism: even if the LLM's conversation
 * context is compressed and the Point 2 reminder text is lost, this
 * push re-injects the reminder into the compressed summary so the
 * LLM still sees it after compaction.
 */
async function compactionHook(input: any, output: any): Promise<void> {
  try {
    const armed = findArmedSession();
    if (!armed.found || !armed.gateSessionId) return;
    if (!output || typeof output.context?.push !== "function") return;

    output.context.push(
      "## Gate Reminder (injected by task-after.ts on compaction)\n" +
        "Compliance gate session `" +
        armed.gateSessionId +
        "` is still ARMED. " +
        'You MUST call `compliance_gate_complete` with `{ "session_id": "' +
        armed.gateSessionId +
        '", "execution_summary": "..." }` when the task finishes. ' +
        "Leaving the gate armed will block the next `git commit` via the pre-commit hook (Layer 0).",
    );
  } catch {
    // Compaction hook is best-effort; never throw
  }
}
