// uc7ks-after.ts — "tool.execute.after" plugin: knowledge pipeline compliance
import { writeLog } from "../lib/log-manager";
import { withPluginLifecycle } from "../lib/hook-lifecycle";
import {
  resolveAgent,
  resolveTaskId,
  resolveDomainId,
} from "../lib/agent-resolver";
import { getModifyPath } from "../lib/tool-scope";
import { normalizeAgentKey, getDomainEntry } from "../lib/uc7ks-schema";
import { atomicWriteSubState } from "../lib/state-utils";
import { incrementAuditCounter } from "../lib/knowledge-audit";
import * as path from "node:path";
import * as fs from "node:fs";

export default withPluginLifecycle("uc7ks-after", {
  "tool.execute.after": toolExecuteAfter,
});

/**
 * FW-UC7KS-DOMAIN-001: Infer domain_id from a file path under docs/official_docs/.
 * Matches the file's subdirectory against knowledge_semantic_map.domains[].save_path.
 * Returns null if no match found.
 */
function inferDomainFromPath(filePath: string): string | null {
  try {
    const root = process.env.OPENCODE_ROOT || process.cwd();
    const configPath = path.join(root, ".opencode", "project.config.json");
    if (fs.existsSync(configPath)) {
      const cfg = JSON.parse(fs.readFileSync(configPath, "utf8"));
      const domains = cfg.knowledge_semantic_map?.domains || [];
      for (const d of domains) {
        if (
          d.save_path &&
          filePath.includes(`docs/official_docs/${d.save_path}`)
        ) {
          return d.domain_id;
        }
      }
    }
  } catch {
    /* best-effort */
  }
  return null;
}

/**
 * after-hook: validate knowledge pipeline compliance
 * - Track cache access for UC7-001 (read on docs/official_docs/)
 * - FW-UC7KS-DOMAIN-001: Write per-domain cache_sufficiency when taskId+domainId available
 * - Validate index.json after cache writes
 */
async function toolExecuteAfter(input: any, output: any): Promise<void> {
  // after-hook: args live in input.args
  const filePath = getModifyPath(input.args || {});

  // Track knowledge cache reads — update knowledge-cache-state.json (P1-B split)
  if (
    input.tool === "read" &&
    filePath &&
    filePath.includes("docs/official_docs/")
  ) {
    const rawAgent = resolveAgent(input.sessionID);
    const agent = normalizeAgentKey(rawAgent);
    const taskId = resolveTaskId(input.sessionID);
    const domainId =
      resolveDomainId(input.sessionID) || inferDomainFromPath(filePath);

    writeLog("uc7ks-after", "runtime", {
      sessionID: input.sessionID,
      callID: input.callID,
      event: "TOOL-AFTER",
      detail: `cache-read | agent=${agent} | file=${filePath} | taskId=${taskId || "none"} | domainId=${domainId || "none"}`,
    });

    // Update knowledge-cache-state.json
    try {
      atomicWriteSubState("knowledge_cache_state", (state) => {
        state.session_access = state.session_access || {};
        state.session_access[agent] = state.session_access[agent] || {};

        // Always update agent-level metadata
        state.session_access[agent].last_read_at = new Date().toISOString();
        state.session_access[agent].last_file_read = filePath;
        state.session_access[agent].total_cache_reads =
          (state.session_access[agent].total_cache_reads || 0) + 1;

        // KC-02 (2026-06-21): Non-fatal audit rollup — count cache hits
        try {
          incrementAuditCounter("total_cache_hits");
        } catch {}

        // Phase 0 (2026-06-18): uc7ks-after NO LONGER auto-writes
        // cache_sufficiency.status="sufficient" or uc7_001_compliant.
        // Reading a docs file proves the agent opened the file, but does
        // NOT prove they understood it or can explain why it was needed.
        //
        // The authoritative read evidence is now generated by the
        // knowledge_cache_attest tool (Phase 1), which cross-verifies
        // against read_audit.jsonl and requires agent-written reason
        // and content_summary.
        //
        // This plugin now ONLY records: last_read_at, last_file_read,
        // total_cache_reads. It also records the file path in the
        // per-domain entry's read_audit_files list for later cross-
        // verification by the attest tool.

        // FW-UC7KS-DOMAIN-001: Record read metadata for per-domain tracking
        // Does NOT write cache_sufficiency.status=sufficient.
        if (taskId && domainId) {
          const domainEntry = getDomainEntry(
            state.session_access,
            agent,
            taskId,
            domainId,
          );
          domainEntry.pipeline_status = "completed";
          domainEntry.declared_at =
            domainEntry.declared_at || new Date().toISOString();
          // Record the read file in a metadata-only field (not cache_sufficiency)
          // Preserve existing cache_sufficiency/discovery/attestation unchanged.
          if (!domainEntry.cache_sufficiency) {
            domainEntry.cache_sufficiency = {
              status: "undeclared",
              missing_topics: [],
              declared_at: new Date().toISOString(),
              reason: "",
              files_read: [],
              content_summary: "",
            };
          }
          writeLog("uc7ks-after", "runtime", {
            sessionID: input.sessionID,
            callID: input.callID,
            event: "UC7KS-READ-METADATA-RECORDED",
            detail: `taskId=${taskId} domainId=${domainId} file=${filePath} | NOTE: NOT auto-setting sufficient — attestation required`,
          });
        }
      });
    } catch (err: any) {
      writeLog("uc7ks-after", "runtime", {
        sessionID: input.sessionID,
        callID: input.callID,
        level: "ERROR",
        event: "TOOL-AFTER",
        detail: "cache-state update failed: " + err.message,
      });
    }
  }
}
