// service/gate/task-tracker.ts — Task completion tracking
// Source: task-after.ts plugin
// Handles: dispatch outcome recording, armed gate reminder, sub-agent session tracking.

import * as fs from "node:fs";
import * as path from "node:path";
import { writeLog } from "../../lib/log-manager";
import { resolveAgent, resolveTaskId } from "../../lib/agent-resolver";
import { capFailedEntries, atomicWriteJson } from "../../lib/state-utils";
import { findArmedSession } from "../../lib/gate-core";
import {
  dbAppendSessionLog,
  dbAppendDispatchFailed,
} from "../../lib/db-state-manager";

const SRC = "service-task-tracker";
const GATE_REMINDER_FILE = ".task_temp/_global/gate-reminder.md";

/**
 * Track task completion after Task() dispatch.
 * Called by task-after plugin.
 *
 * Steps:
 *   1. Record dispatch outcome (SUCCESS/FAILURE)
 *   2. On failure: record to dispatch_failed_log DB
 *   3. On success: armed gate reminder + sub-agent session tracking + DB dispatch consume
 */
export function trackTaskComplete(params: {
  sessionID: string;
  callID: string;
  tool: string;
  args: Record<string, unknown>;
  output: any;
}): void {
  const isTask = params.tool === "Task" || params.tool === "task";
  if (!isTask) return;

  const agent = resolveAgent(params.sessionID);
  const taskId = resolveTaskId(params.sessionID);
  const outcome = params.output?.error || params.output?.failed ? "FAILURE" : "SUCCESS";
  const rawError = (params.output?.error || params.output?.failed || "").toString();
  const isFailure = outcome === "FAILURE";

  writeLog("task-after", "runtime", {
    sessionID: params.sessionID,
    callID: params.callID,
    agent,
    agentType: (params.args as any)?.subagent_type || "?",
    level: isFailure ? "ERROR" : "INFO",
    event: isFailure ? "DISPATCH-TASK-FAILED" : "DISPATCH-TASK-SUCCESS",
    detail: `phase=task | outcome=${outcome} | dagTaskId=${taskId || "(none)"}` +
            ` | agentTarget=${(params.args as any)?.subagent_type || "?"}` +
            ` | rawError=${rawError.slice(0, 500)}`,
  });

  // ── On failure: record to dispatch_failed_log DB ──
  if (isFailure) {
    try {
      dbAppendDispatchFailed({
        dispatchId: params.callID || "unknown",
        agentType: (params.args as any)?.subagent_type || "unknown",
        dagTaskId: taskId || undefined,
        sessionId: params.sessionID,
        createdAt: Date.now(),
        failedAt: Date.now(),
        reason: "task-failure",
        errorMsg: (params.output?.error || params.output?.failed || "unknown").toString(),
      });
    } catch (err: any) {
      writeLog("task-after", "runtime", {
        sessionID: params.sessionID, callID: params.callID, agent,
        level: "ERROR", event: "TOOL-AFTER",
        detail: "failure-record failed: " + err.message,
      });
    }
    return;
  }

  // ── On success: armed gate fallback reminder ──
  try {
    const armed = findArmedSession();
    if (armed.found && armed.gateSessionId) {
      const root = process.env.OPENCODE_ROOT || ".";
      const rf = path.join(root, GATE_REMINDER_FILE);
      const dir = path.dirname(rf);
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

      const dispatchedAgent = (params.args as any)?.subagent_type || agent || "unknown";
      const ts = new Date().toISOString();

      const atomicWriteText = (target: string, text: string): void => {
        const tmp = `${target}.tmp.${process.pid}`;
        fs.writeFileSync(tmp, text, "utf8");
        fs.renameSync(tmp, target);
      };

      const mdContent =
        "# Gate Reminder (auto-generated by task-after.ts)\n\n" +
        "- **Status**: gate session `" + armed.gateSessionId + "` is still ARMED\n" +
        "- **Last dispatch**: `" + dispatchedAgent + "` completed task `" +
          (taskId || "(none)") + "` at " + ts + "\n" +
        "- **Required action**: call `compliance_gate_complete` with\n" +
          "  ```json\n" +
          '  { "session_id": "' + armed.gateSessionId + '", "execution_summary": "..." }\n' +
          "  ```\n" +
        "- **Why**: leaving the gate armed will block the next `git commit` via the pre-commit hook (Layer 0).\n";
      atomicWriteText(rf, mdContent);

      atomicWriteJson(rf.replace(/\.md$/, ".json"), {
        session_id: armed.gateSessionId,
        last_dispatched_agent: dispatchedAgent,
        last_task_id: taskId || null,
        written_at: ts,
        note: "This file is the Point 3 FALLBACK reminder. The PRIMARY reminder lives in the LLM conversation context.",
      });

      writeLog("task-after", "runtime", {
        sessionID: params.sessionID, callID: params.callID, agent,
        level: "WARN", event: "GATE-REMINDER-WRITTEN",
        detail: `armed session ${armed.gateSessionId} still open after dispatch of ${dispatchedAgent}`,
      });
    }
  } catch (err: any) {
    writeLog("task-after", "runtime", {
      sessionID: params.sessionID, callID: params.callID, agent,
      level: "WARN", event: "GATE-REMINDER-FAILED",
      detail: "armed-session reminder skipped: " + err.message,
    });
  }

  // ── Sub-agent session tracking + DB dispatch consume ──
  try {
    const subSessionId = params.output?.metadata?.sessionId;
    if (!subSessionId) return;

    const root = process.env.OPENCODE_ROOT || ".";
    let dagTaskId: string | null = null;

    // Try per-dispatch ctx/ files (isolated, race-free)
    try {
      const ctxDir = path.join(root, ".task_temp", "_dispatch", "ctx");
      if (fs.existsSync(ctxDir)) {
        const files = fs.readdirSync(ctxDir).filter((f) => f.endsWith(".json"));
        if (files.length > 0) {
          const latest = files.reduce((a, b) => {
            const sa = fs.statSync(path.join(ctxDir, a));
            const sb = fs.statSync(path.join(ctxDir, b));
            return sa.mtimeMs > sb.mtimeMs ? a : b;
          });
          const ctx = JSON.parse(fs.readFileSync(path.join(ctxDir, latest), "utf8"));
          dagTaskId = ctx.dagTaskId || null;
          fs.unlinkSync(path.join(ctxDir, latest));
          writeLog("task-after", "runtime", {
            sessionID: params.sessionID,
            event: "DISPATCH-CTX-CLEANUP",
            detail: `Per-dispatch context cleaned: ctx/${latest}`,
          });
        }
      }
    } catch {}

    if (!dagTaskId) dagTaskId = resolveTaskId(params.sessionID);
    if (!dagTaskId) return;

    const subAgentType = (params.args as any)?.subagent_type || agent || "unknown";
    const runId = process.env.OPENCODE_RUN_ID || null;
    dbAppendSessionLog(subSessionId, dagTaskId, subAgentType, runId);
    writeLog("task-after", "runtime", {
      sessionID: params.sessionID, callID: params.callID, agent,
      event: "SESSION-LOG-APPENDED",
      detail: `sub-agent sessionId=${subSessionId} dagTaskId=${dagTaskId} agentType=${subAgentType}`,
    });

    // DB-canonical dispatch consume
    try {
      const {
        dbConsumeDispatch,
        dbInsertDispatchAttempt,
        dbGetDispatchQueue,
      } = require("../../lib/dispatch-db");

      const runningEntries = dbGetDispatchQueue("running", subAgentType, 5);
      const match = runningEntries.find(
        (e: any) =>
          e.dag_task_id === dagTaskId &&
          (e.lease_owner === subSessionId || e.lease_owner === params.sessionID),
      );

      if (match) {
        dbConsumeDispatch(match.id, subSessionId);
        dbInsertDispatchAttempt(match.id, 1, "success", subSessionId);
        writeLog("task-after", "runtime", {
          sessionID: params.sessionID, callID: params.callID, agent,
          event: "DISPATCH-QUEUE-CONSUME",
          detail: `Consumed dispatch queueId=${match.id} dagTaskId=${dagTaskId}`,
        });
      } else {
        writeLog("task-after", "runtime", {
          sessionID: params.sessionID, callID: params.callID, agent,
          event: "DISPATCH-QUEUE-CONSUME-NO-MATCH",
          detail: `No running DB entry for dagTaskId=${dagTaskId} agentType=${subAgentType}`,
        });
      }
    } catch (e: any) {
      writeLog("task-after", "runtime", {
        sessionID: params.sessionID, callID: params.callID, agent,
        level: "WARN", event: "DISPATCH-DB-CONSUME-FAILED",
        detail: `DB dispatch consume failed: ${e.message}`,
      });
    }
  } catch {
    // Session log persistence is best-effort
  }
}

/**
 * Get gate reminder text for compaction hook.
 * Returns null if no armed session.
 */
export function getGateReminderText(): string | null {
  try {
    const armed = findArmedSession();
    if (!armed.found || !armed.gateSessionId) return null;
    return (
      "## Gate Reminder (injected by task-after.ts on compaction)\n" +
      "Compliance gate session `" + armed.gateSessionId + "` is still ARMED. " +
      'You MUST call `compliance_gate_complete` with `{ "session_id": "' +
      armed.gateSessionId +
      '", "execution_summary": "..." }` when the task finishes. ' +
      "Leaving the gate armed will block the next `git commit` via the pre-commit hook (Layer 0)."
    );
  } catch {
    return null;
  }
}
