#!/usr/bin/env bun
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';

const PROJECT_ROOT = path.resolve(__dirname, '..', '..', '..');

/**
 * @deprecated CodeGraph MCP 已替代 Scout 层的代码结构分析功能。
 * 保留此脚本仅用于历史兼容。新任务应使用 codegraph_impact / codegraph_callers。
 * 退役日期: 2026-06-27
 */
/**
 * scout-extractor.js — UC7KS Scout Findings Extractor v1.0.0
 *
 * Converts raw Scout subagent output into structured .md files
 * saved under docs/official_docs/{domain}/{library}/source-analysis/.
 *
 * Extraction steps:
 *  1. Parse Scout output for file paths, line numbers, code snippets
 *  2. Structure into standardized .md format with metadata header
 *  3. Save to source-analysis/ with source: "scout" metadata for index.json
 *  4. Return the file path for @Knowledge-Curator to register in index.json
 *
 * Usage:
 *   bun .opencode/scripts/knowledge/scout-extractor.ts <domain> <library> <topic> <scout_output_text>
 *   OR pipe Scout output via stdin: echo "..." | bun .opencode/scripts/knowledge/scout-extractor.ts backend nestjs "guard-execution-order"
 */


const DOCS_DIR = path.join(PROJECT_ROOT, "docs", "official_docs");

function extract({ domain, library, topic, scoutOutput, repoUrl, question }) {
  const slug = topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
  const dir = path.join(DOCS_DIR, domain, library, "source-analysis");
  fs.mkdirSync(dir, { recursive: true });

  const filePath = path.join(dir, `${slug}.md`);
  const now = new Date().toISOString();

  // Structured markdown header
  const content = `# ${topic} — Source Code Analysis

**Repository**: ${repoUrl || "N/A"}
**Date**: ${now.slice(0, 10)}
**Source**: Scout (OpenCode built-in subagent)
**Layer**: 3 — Source Code Analysis
**TTL**: 14 days (shorter than standard 30-day for documentation)

## Question
${question || "N/A"}

## Findings
${scoutOutput || "No findings returned from Scout."}

## Metadata
- Extracted by: UC7KS Scout Extractor v1.0.0
- Domain: ${domain}
- Library: ${library}
- SHA-256: sha256:${crypto.createHash("sha256").update(scoutOutput || "").digest("hex")}

## Usage
This document was generated by Layer 3 (Scout) of the UC7KS knowledge acquisition pipeline.
Unlike documentation-tier sources (Context7/webfetch), this contains source-code-level analysis
and may become stale with new library releases. Re-analyze after TTL expiry (14 days).
`;

  fs.writeFileSync(filePath, content, "utf-8");

  const stat = fs.statSync(filePath);
  const sha256 = crypto.createHash("sha256").update(content).digest("hex");

  return {
    path: path.relative(DOCS_DIR, filePath),
    absolute_path: filePath,
    source: "scout",
    sha256: `sha256:${sha256}`,
    size_bytes: stat.size,
    domain,
    library,
    topic: slug,
    ttl_days: 14,
  };
}



export { extract };

